app/urls.py
from django.urls import path, include

from app.views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('signupDoctor/', signupDoctor, name='signupDoctor'),
    path('signupPatient/', signupPatient, name='signupPatient'),

    
    path('doctorList/', doctorList, name='doctorList'),
    path('appointmententList/', appointmententList, name='appointmententList'),

    path('makeAppointment/', makeAppointment, name='makeAppointment'),
    path('appointmententStatus/', appointmententStatus, name='appointmententStatus'),
    path('makeSelectedDrAppointment/<int:pk>/', makeSelectedDrAppointment, name='makeSelectedDrAppointment'),

    
    path('adminPanel/', adminPanel, name='adminPanel'),
    path('doctorApprove/<int:pk>/', doctorApprove, name='doctorApprove'),
    path('doctorRefuse/<int:pk>/', doctorRefuse, name='doctorRefuse'),
    path('bookingApprove/<int:pk>/', bookingApprove, name='bookingApprove'),
    path('bookingRefuse/<int:pk>/', bookingRefuse, name='bookingRefuse'),

]

appointment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

templates/adminPanel.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div style="height:50px"></div>

{% if doctors %}
<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center">All Doctors List</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div class="container-fluid px-5">
    <table class="table table-striped table-hover" id="jsDataTableLib">
        <thead>
          <tr>
            <th scope="col">username</th>
            <th scope="col">firstName</th>
            <th scope="col">lastName</th>
            <th scope="col">email</th>
            <th scope="col">dateOfBirth</th>
            <th scope="col">address</th>
            <th scope="col">contactNo</th>
            <th scope="col">degree</th>
            <th scope="col">speciality</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for i in doctors %}
            <tr>
                <th scope="row">{{i.user.username}}</th>
                <td>{{i.user.firstName}}</td>
                <td>{{i.user.lastName}}</td>
                <td>{{i.user.email}}</td>
                <td>{{i.user.dateOfBirth}}</td>
                <td>{{i.user.address}}</td>
                <td>{{i.user.contactNo}}</td>
                <td>{{i.degree}}</td>
                <td>{{i.speciality}}</td>
                {% if i.isApproved %}
                <td style="color: green;">Verified</td>
                {% else %}
                <td style="color: Red;">Not Verified</td>
                {% endif %}

                {% if i.isApproved %}
                <td><a href="{% url 'app:doctorRefuse' pk=i.pk %}" class="btn btn-warning" style="color: white;">Refuse</a></td>
                {% else %}
                <td><a href="{% url 'app:doctorApprove' pk=i.pk %}" class="btn btn-success">Approve</a></td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% else %}
<h3 class="text-center">No Doctor Found</h3>
{% endif %}





<div style="height:100px"></div>

{% if patients %}
<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center">All Patients List</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div class="container-fluid px-5">
    <table class="table table-striped table-hover" id="jsDataTableLib2">
        <thead>
          <tr>
            <th scope="col">username</th>
            <th scope="col">firstName</th>
            <th scope="col">lastName</th>
            <th scope="col">email</th>
            <th scope="col">dateOfBirth</th>
            <th scope="col">address</th>
            <th scope="col">contactNo</th>
            <th scope="col">gender</th>
          </tr>
        </thead>
        <tbody>
            {% for i in patients %}
            <tr>
                <th scope="row">{{i.user.username}}</th>
                <td>{{i.user.firstName}}</td>
                <td>{{i.user.lastName}}</td>
                <td>{{i.user.email}}</td>
                <td>{{i.user.dateOfBirth }}</td>
                <td>{{i.user.address}}</td>
                <td>{{i.user.contactNo}}</td>
                <td>{{i.gender}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% else %}
<h3 class="text-center">No Patient Found</h3>
{% endif %}




<div style="height:100px"></div>

{% if appoinments %}
<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center">All Appoinments List</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div class="container-fluid px-5">
    <table class="table table-striped table-hover" id="jsDataTableLib3">
        <thead>
          <tr>
            <th scope="col">date</th>
            <th scope="col">patient full name</th>
            <th scope="col">doctor name</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for i in appoinments %}
            <tr>
                <th scope="row">{{i.date}}</th>
                <td>{{i.pname.user.firstName}} {{i.pname.user.lastName}}</td>
                <td>{{i.doctor.user.firstName}} {{i.doctor.user.lastName}}</td>
                {% if i.isConfiremed %}
                <td style="color: green;">Confirmed</td>
                {% else %}
                <td style="color: red;">Watting for Approval</td>
                {% endif %}
                
                {% if i.isConfiremed %}
                <td><a href="{% url 'app:bookingRefuse' pk=i.pk %}" class="btn btn-warning" style="color: white;">Cancel Booking</a></td>
                {% else %}
                <td><a href="{% url 'app:bookingApprove' pk=i.pk %}" class="btn btn-success">Confirm Booking</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% else %}
<h3 class="text-center">No Appoinment Found</h3>
{% endif %}










<div style="height:200px"></div>

{% endblock %}

{% block script %}


<style>
    nav{
        box-shadow: 0px 0px 1px 0px rgba(0,0,0,0.5);
    }
    .mybg{        
        height: 240px;
    }
    .subtitleBlue{
        font-size: 15px;
        line-height: 1.5;
        font-weight: 600;
        font-family: "Poppins", Arial, sans-serif;
        color: #3c97e8;
    }
    .subtitleGrey{
        font-size: 12px;
        font-weight: 300;
        font-family: "Poppins", Arial, sans-serif;
        color: #868686;
    }
    .mybtn{
        background-color: #9bdf46;
        color:white !important;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .mybtn:hover{
        border: 2px solid #9bdf46 !important;
        color: #8de225 !important;
        background-color: white;
    }
</style>




{% endblock %}

templates/appointmententList.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div style="height:50px"></div>

{% if appoinments %}
<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center">All Appoinments List</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div class="container-fluid px-5">
    <table class="table table-striped table-hover" id="jsDataTableLib3">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Patient Full Name</th>
            <th scope="col">Doctor Name</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
            {% for i in appoinments %}
            <tr>
                <th scope="row">{{i.date}}</th>
                <td>{{i.pname.user.firstName}} {{i.pname.user.lastName}}</td>
                <td>{{i.doctor.user.firstName}} {{i.doctor.user.lastName}}</td>
                {% if i.isConfiremed %}
                <td style="color: green;">Confirmed</td>
                {% else %}
                <td style="color: red;">Waiting for Approval</td>
                {% endif %}
                
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% else %}
<h3 class="text-center">No Appoinment Found</h3>
{% endif %}










<div style="height:200px"></div>

{% endblock %}

{% block script %}


<style>
    nav{
        box-shadow: 0px 0px 1px 0px rgba(0,0,0,0.5);
    }
    .mybg{        
        height: 240px;
    }
    .subtitleBlue{
        font-size: 15px;
        line-height: 1.5;
        font-weight: 600;
        font-family: "Poppins", Arial, sans-serif;
        color: #3c97e8;
    }
    .subtitleGrey{
        font-size: 12px;
        font-weight: 300;
        font-family: "Poppins", Arial, sans-serif;
        color: #868686;
    }
    .mybtn{
        background-color: #9bdf46;
        color:white !important;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .mybtn:hover{
        border: 2px solid #9bdf46 !important;
        color: #8de225 !important;
        background-color: white;
    }
</style>




{% endblock %}

templates/appointmententStatus.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div style="height:50px"></div>

{% if appoinments %}
<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center">All Appoinments List</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div class="container-fluid px-5">
    <table class="table table-striped table-hover" id="jsDataTableLib3">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Patient Full Name</th>
            <th scope="col">Doctor Name</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
            {% for i in appoinments %}
            <tr>
                <th scope="row">{{i.date}}</th>
                <td>{{i.pname.user.firstName}} {{i.pname.user.lastName}}</td>
                <td>{{i.doctor.user.firstName}} {{i.doctor.user.lastName}}</td>
                {% if i.isConfiremed %}
                <td style="color: green;">Confirmed</td>
                {% else %}
                <td style="color: red;">Waiting for Approval</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% else %}
<h3 class="text-center">No Appoinment Found</h3>
{% endif %}










<div style="height:200px"></div>

{% endblock %}

{% block script %}


<style>
    nav{
        box-shadow: 0px 0px 1px 0px rgba(0,0,0,0.5);
    }
    .mybg{        
        height: 240px;
    }
    .subtitleBlue{
        font-size: 15px;
        line-height: 1.5;
        font-weight: 600;
        font-family: "Poppins", Arial, sans-serif;
        color: #3c97e8;
    }
    .subtitleGrey{
        font-size: 12px;
        font-weight: 300;
        font-family: "Poppins", Arial, sans-serif;
        color: #868686;
    }
    .mybtn{
        background-color: #9bdf46;
        color:white !important;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .mybtn:hover{
        border: 2px solid #9bdf46 !important;
        color: #8de225 !important;
        background-color: white;
    }
</style>




{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title></title>

    <meta charset="UTF-8">

  	<!-- media queary support -->
  	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  	<!-- Latest compiled and minified CSS -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  	<!-- jQuery library -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  	<!-- Popper JS -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  	<!-- Latest compiled JavaScript -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  	<!-- animated css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>

  	<!-- font awsome css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  	<!-- poppins font link -->
  	<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

  	<!-- roboto font link -->
  	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

  	<!-- custom css link -->
  	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

  </head>
  <body>

    <div class="container-fluid">
      <div class="row m-0" style="padding-left: 90px; padding-right: 80px;padding-top: 10px;">
          <a href="{% url 'app:index' %}" style="font-size: 36px; font-weight: 700;">
            <span style="color:#3c97e8;">DR</span>
            <span style="color:#9bdf46;">Appointment</span>
          </a>

        <div class="col-md-2 ml-auto">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/phn.png' %}" style="max-height: 40px;"></span>
                <p>Call Us<br>02-999-333</p>
            </div>
        </div>

        <div class="col-md-3 ml-4">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/phn.png' %}" style="max-height: 40px;"></span>
                <p>Address<br>50/A Green Road, Dhaka</p>
            </div>
        </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light py-3" style="padding-left: 80px;padding-right: 80px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active mx-4">
              <a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mx-4">
              <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="{% url 'app:doctorList' %}">Meet Our Doctors</a>
            </li>
            <!-- <li class="nav-item mx-4">
                <a class="nav-link" href="#">Services</a>
            </li> -->
            <li class="nav-item mx-4">
                <a class="nav-link" href="#">Feedback</a>
            </li>

            
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link mx-3" href="#">Hi {{request.user.username}}!</a>
            <li class="nav-item">
                <a href="{% url 'app:signout' %}" class="btn nav-link" style="background-color: #9bdf46; color:white; width:100px; height:40px; border-radius:40px;">Logout</a>
            </li>
            {% else %}
            <li class="nav-item" data-toggle="modal" data-target="#loginModal">
                <a href="#" class="btn nav-link" style="background-color: #9bdf46; color:white; width:100px; height:40px; border-radius:40px;">Login</a>
            </li>
            {% endif %}
        </ul>
            
        </div>
      </nav>



    {% block content %}

    {% endblock %}







    
<!-- login modal start -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title login-modal-title" id="loginModalLabel">Welcome back</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'app:signin' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name</label>
                        <input type="text" class="form-control" name="username" placeholder="User name">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>

                    <div style="height: 80px;"></div>

                    <p class="modal-forgorpass text-center">
                        <a href="#">Forgot password?</a>
                    </p>
                    <input type="submit" class="btn login-submit mt-2 ml-3" name="login" value="Login" style="background-color: #64B53B;">
                    <p class="need-acnt text-center mt-3">
                        Need an account?
                        <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#registerModal" data-dismiss="modal" aria-label="Close">
                            Sign up
                        </a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- login modal end -->

<!-- register modal start -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title reg-modal-title" id="registerModalLabel">Sign up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body py-5">

                <a href="{% url 'app:signupPatient' %}" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/student.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as a patient</p>
                </a>
                <a href="{% url 'app:signupDoctor' %}" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/teacher.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as a doctor</p>
                </a>
                <a href="#" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/administrator.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as an admin</p>
                </a>

            </div>
            <div class="modal-footer">
                <p class="need-acnt text-center mt-2 mx-auto">
                    Have an account?
                    <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#loginModal" data-dismiss="modal" aria-label="Close">
                        Login
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- register modal end -->




  </body>
</html>


<style>
    body{
      font-family: 'Poppins', sans-serif;
    }
    a:hover{
        text-decoration: none;
    }
</style>


<!-- Table Sorting Library -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
    $('#jsDataTableLib').DataTable();
    $('#jsDataTableLib2').DataTable();
    $('#jsDataTableLib3').DataTable();
    $('#jsDataTableLib4').DataTable();
} );
</script>

templates/doctorList.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid mybg">
    <div class="col-xl-6 mx-auto m-0">
        <h2 class="text-center" style="color: white; font-weight: 600;">Meet Our Doctor</h2>
        <p class="subtitleBlue text-center">The largest and most respected accreditation agencies</p>
    </div>
</div>

<div style="height: 50px;"></div>

<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="card-group">
          {% for i in doctors %}
            <div class="card col-xl-3 mx-4">
              <img class="card-img-top" src="https://a6e8z9v6.stackpathcdn.com/mediz/hospital/wp-content/uploads/sites/2/2019/12/p-8-300x300.jpg" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">{{ i.user.firstName }} {{ i.user.lastName }}</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
              <a href="{% url 'app:makeSelectedDrAppointment' pk=i.pk %}" class="btn btn-info" style="color: white;">Get Appoinment</a>
              <div class="card-footer">
                <small class="text-muted">{{ i.speciality }}</small>
              </div>
            </div>
          {% endfor %}
            
          </div>
    </div>
</div>

<div style="height: 50px;"></div>

<style>
    .mybg{        
        background-image:url(" {% static 'imgs/hospital.jpg' %} ");
        background-size: cover;
        height: 260px;
        padding-top: 80px;
    }
    .subtitleBlue{
        font-size: 18px;
        line-height: 1.5;
        font-weight: 400;
        font-family: "Poppins", Arial, sans-serif;
        color: white;
    }
    .subtitleGrey{
        font-size: 12px;
        font-weight: 300;
        font-family: "Poppins", Arial, sans-serif;
        color: #868686;
    }
    .card-text{
        font-size: 12px;
    }
    .mybtn{
        background-color: #9bdf46;
        color:white !important;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .mybtn:hover{
        border: 2px solid #9bdf46 !important;
        color: #8de225 !important;
        background-color: white;
    }
</style>




{% endblock %}

templates/index.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid mybg">

    <div class="row">
        <div class="col-xl-1"></div>
        <div class="col-md-6" style="margin-top:160px;">
            <div class="">
                <h1 class="my-3">Your Health <strong>is always <br>in the first place</strong></h1>
                <h2 class="my-3 subtitle">Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</h2>
                {% if request.user.isPatient %}
                <p><a class="btn mybtn pt-3" href="{% url 'app:makeAppointment' %}">Make an Appointment</a></p>
                <p><a class="btn mybtn pt-3" href="{% url 'app:appointmententStatus' %}">Appointment Status</a></p>
                {% elif request.user.isDoctor %}
                <p><a class="btn mybtn pt-3" href="{% url 'app:appointmententList' %}">Watch all Appointment</a></p>
                {% elif request.user.is_superuser %}
                <p><a class="btn mybtn pt-3" href="{% url 'app:adminPanel' %}">Explore Admin Panel</a></p>
                {% else %}
                <p><a class="btn mybtn pt-3" data-toggle="modal" data-target="#loginModal">Explore</a></p>
                {% endif %}
            </div>
        </div>
    </div>

</div>





<style>
    .mybg{
        background-image: 
        linear-gradient(to right, white 0%, white 35%, rgba(255, 255, 255, 0) 79%, rgba(255, 255, 255, 0) 100%),
        url(" {% static 'imgs/bg1.jpg' %} ");
        min-height: 560px;
    }
    .subtitle{
        font-size: 20px;
        line-height: 1.5;
        margin-bottom: 30px;
        font-weight: 300;
        font-family: "Poppins", Arial, sans-serif;
        color: rgba(0, 0, 0, 0.5);
    }
    .mybtn{
        background-color: #9bdf46;
        color:white !important;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .mybtn:hover{
        border: 2px solid #9bdf46 !important;
        color: #8de225 !important;
        background-color: white;
    }
</style>




{% endblock %}

templates/makeAppointment.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid mybg">

    <div class="row m-0 d-flex justify-content-center" style="margin-top: 80px;">
        <div class="col-xl-7 bg-light p-5">
            <h3 class="my-3">Book an <strong>Appointment</h3>
            <form method="POST" class="col-xl-6 my-5">
                {% csrf_token %}
                
                <div class="form-group">
                    <label class="myForm">Patient Name</label>
                    <input type="text" name="pname" value="{{request.user.username}}" class="form-control" disabled>
                </div>

                <div class="form-group">
                    <label class="myForm">Doctor Name</label>
                    <select name="doctorpk" class="form-control">
                        {% if selected_Doctor  is not None %}
                        <option value="{{selected_Doctor.pk}}">{{selected_Doctor.user}}</option>
                        <br>
                        {% endif %}
                        {% for i in doctor %}
                        <option value="{{i.pk}}">{{i.user}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label class="myForm">Date and Time</label>
                    <input type="datetime-local" name="date" class="form-control">
                </div>


                <div class="row m-0">
                    <button type="submit" class="mybtn">Submit</button>
                </div>

            </form>
        </div>
        <div class="col-xl-6">
            <img src="https://images.unsplash.com/photo-1518281361980-b26bfd556770?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=405&q=80" alt="">
        </div>
    </div>

</div>












<style>
    
    .mybtn{
        background-color: #9bdf46;
        color:white;
        width:240px;
        height:50px; 
        border-radius:50px;
        border: none !important;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
    }
    .form-control{
        
        border-bottom: 3px solid #9bdf46;
    }
    .myForm{
        font-weight: normal;
        font-size: 14px;
    }
</style>




{% endblock %}